=== joaocampinhos/pmp2/java-ml.dtd
<!-- java-ml.dtd 0.96 -->
<!-- Copyright (C) 2000, Greg J. Badros <gjb@cs.washington.edu> -->
<!-- A DTD for JavaML, an XML representation of Java Source Code -->
<!-- http://www.cs.washington.edu/homes/gjb/papers/javaml/javaml.html -->

<!ENTITY % visibility-attribute "visibility (public|private|protected) #IMPLIED">
<!ENTITY % interface-visibility-attribute "visibility (public) #IMPLIED">
<!ENTITY % kind-attribute "kind (integer|long|float|double) #IMPLIED">
<!ENTITY % mod-final "final CDATA #IMPLIED">
<!ENTITY % mod-static "static CDATA #IMPLIED">
<!ENTITY % mod-volatile "volatile CDATA #IMPLIED">
<!ENTITY % mod-transient "transient CDATA #IMPLIED">
<!ENTITY % mod-native "native CDATA #IMPLIED">
<!ENTITY % mod-abstract "abstract CDATA #IMPLIED">
<!ENTITY % mod-synchronized "synchronized CDATA #IMPLIED">
<!ENTITY % location-info 
	"line CDATA #IMPLIED col CDATA #IMPLIED 
         end-line CDATA #IMPLIED end-col CDATA #IMPLIED
	 comment CDATA #IMPLIED">
<!ENTITY % expr-elems "send|new|new-array|var-ref|field-access|array-ref|paren|assignment-expr|conditional-expr|binary-expr|unary-expr|cast-expr|instanceof-test|literal-number|literal-string|literal-char|literal-boolean|literal-null|this|super">
<!ENTITY % stmt-elems "block|local-variable|try|throw|if|switch|loop|do-loop|return|continue|break|synchronized|%expr-elems;">

<!ELEMENT code-fragment ANY>
<!ELEMENT result ANY>
<!ELEMENT java-source-program (java-class-file+)>
<!ELEMENT java-class-file (package-decl?,import*,(class|interface)+) >
<!ATTLIST java-class-file
    name CDATA #IMPLIED
    version CDATA #IMPLIED>
<!ELEMENT import EMPTY>
<!ATTLIST import
    module CDATA #REQUIRED>
<!ELEMENT class (superclass?, implement*, (class|interface|constructor|method|field|static-initializer|instance-initializer)*) >
<!ATTLIST class
    name CDATA #REQUIRED
    %visibility-attribute;
    %mod-static;
    %mod-abstract;
    %mod-final;
    %mod-synchronized;
    %location-info;>
<!ELEMENT anonymous-class (superclass?, implement*, (constructor|method|field|instance-initializer)*) >
<!ATTLIST anonymous-class
    %mod-abstract;
    %mod-final;
    %mod-synchronized;
    %location-info;>
<!ELEMENT superclass EMPTY>
<!ATTLIST superclass
    name CDATA #REQUIRED>
<!ELEMENT interface (extend*, (method|field)*) >
<!ATTLIST interface
    name CDATA #REQUIRED
    %interface-visibility-attribute;
    %location-info;>
<!ELEMENT implement EMPTY>
<!ATTLIST implement
    interface CDATA #REQUIRED>
<!ELEMENT extend EMPTY>
<!ATTLIST extend
    interface CDATA #REQUIRED>
<!ELEMENT field (type,(array-initializer|%expr-elems;)?)>
<!ATTLIST field
    name CDATA #REQUIRED
    %visibility-attribute;
    %mod-final;
    %mod-static;
    %mod-volatile;
    %mod-transient;
    %location-info;>
<!ELEMENT constructor (formal-arguments,throws*,(super-call|this-call)?,(%stmt-elems;)?)>
<!ATTLIST constructor
    name CDATA #REQUIRED
    id ID #REQUIRED
    %visibility-attribute;
    %mod-final;
    %mod-static;
    %mod-synchronized;
    %mod-volatile;
    %mod-transient;
    %mod-native;
    %location-info;>
<!ELEMENT method (type,formal-arguments,throws*,(%stmt-elems;)?)>
<!ATTLIST method 
    name CDATA #REQUIRED
    id ID #REQUIRED
    %visibility-attribute;
    %mod-abstract;
    %mod-final;
    %mod-static;
    %mod-synchronized;
    %mod-volatile;
    %mod-transient;
    %mod-native;
    %location-info;>
<!ELEMENT formal-arguments (formal-argument)*>
<!ELEMENT formal-argument (type)>
<!ATTLIST formal-argument
    name CDATA #REQUIRED
    id ID #REQUIRED
    %mod-final;>
<!ELEMENT send (target?,arguments)>
<!ATTLIST send
    message CDATA #REQUIRED
    idref IDREF #IMPLIED>
<!ELEMENT block (label*,(%stmt-elems;)*)>
<!ATTLIST block
    %location-info;>
<!ELEMENT label EMPTY>
<!ATTLIST label
    name CDATA #REQUIRED>
<!ELEMENT target (%expr-elems;)>
<!ELEMENT return (%expr-elems;)?>
<!ELEMENT throw (%expr-elems;)>
<!ELEMENT throws EMPTY>
<!ATTLIST throws
    exception CDATA #REQUIRED>
<!ELEMENT new (type,arguments,anonymous-class?)>
<!ELEMENT type EMPTY>
<!ATTLIST type
    primitive CDATA #IMPLIED
    name CDATA #REQUIRED
    dimensions CDATA #IMPLIED
    idref IDREF #IMPLIED>
<!ELEMENT new-array (type,dim-expr*,array-initializer?)>
<!ATTLIST new-array
    dimensions CDATA #REQUIRED>
<!ELEMENT dim-expr (%expr-elems;)>
<!ELEMENT local-variable (type,(static-initializer|array-initializer|%expr-elems;)?)>
<!ATTLIST local-variable
    name CDATA #REQUIRED
    id ID #REQUIRED
    continued CDATA #IMPLIED
    %mod-final;>
<!ELEMENT array-initializer (array-initializer|%expr-elems;)*>
<!ATTLIST array-initializer
    length CDATA #REQUIRED>
<!ELEMENT arguments (%expr-elems;)*>
<!ELEMENT literal-string EMPTY>
<!ATTLIST literal-string
    value CDATA #REQUIRED>
<!ELEMENT literal-char EMPTY>
<!ATTLIST literal-char
    value CDATA #REQUIRED>
<!ELEMENT literal-number EMPTY>
<!ATTLIST literal-number
    value CDATA #REQUIRED
    %kind-attribute;
    base CDATA "10">
<!ELEMENT var-ref EMPTY>
<!ATTLIST var-ref
    name CDATA #REQUIRED
    idref IDREF #IMPLIED>
<!ELEMENT field-access (%expr-elems;)>
<!ATTLIST field-access
    field CDATA #REQUIRED>
<!ELEMENT var-set EMPTY>
<!ATTLIST var-set
    name CDATA #REQUIRED>
<!ELEMENT field-set (%expr-elems;)>
<!ATTLIST field-set
    field CDATA #REQUIRED>
<!ELEMENT package-decl EMPTY>
<!ATTLIST package-decl
    name CDATA #REQUIRED>
<!ELEMENT assignment-expr (lvalue,(%expr-elems;))>
<!ATTLIST assignment-expr
    op CDATA #REQUIRED>
<!ELEMENT lvalue (var-set|field-set|%expr-elems;)>
<!ELEMENT instanceof-test ((%expr-elems;),type)>
<!ELEMENT binary-expr ((%expr-elems;),(%expr-elems;))>
<!ATTLIST binary-expr
    op CDATA #REQUIRED>
<!ELEMENT paren (%expr-elems;)>
<!ELEMENT unary-expr (%expr-elems;)>
<!ATTLIST unary-expr
    op CDATA #REQUIRED
    post (true|false) #IMPLIED>
<!ELEMENT cast-expr (type,(%expr-elems;))>
<!ELEMENT literal-boolean EMPTY>
<!ATTLIST literal-boolean
    value (true|false) #REQUIRED>
<!ELEMENT literal-null EMPTY>
<!ELEMENT synchronized (expr,block)>
<!ELEMENT expr (%expr-elems;)>
<!ELEMENT if (test,true-case,false-case?)>
<!ELEMENT test (%expr-elems;)>
<!ELEMENT true-case (%stmt-elems;)?>
<!ELEMENT false-case (%stmt-elems;)?>
<!ELEMENT array-ref (base,offset)>
<!ELEMENT base (%expr-elems;)>
<!ELEMENT offset (%expr-elems;)>
<!ELEMENT static-initializer (%stmt-elems;)*>
<!ELEMENT instance-initializer (%stmt-elems;)*>
<!ELEMENT super-call (arguments)>
<!ELEMENT this-call (arguments)>
<!ELEMENT super EMPTY>
<!ELEMENT this EMPTY>
<!ELEMENT loop (init*,test?,update*,(%stmt-elems;)?)>
<!ATTLIST loop
    kind (for|while) #IMPLIED
    %location-info;>
<!ELEMENT init (local-variable|%expr-elems;)*>
<!ELEMENT update (%expr-elems;)>
<!ELEMENT do-loop ((%stmt-elems;)?,test?)>
<!ELEMENT try ((%stmt-elems;),catch*,finally?)>
<!ELEMENT catch (formal-argument,(%stmt-elems;)?)>
<!ELEMENT finally (%stmt-elems;)>
<!ELEMENT continue EMPTY>
<!ATTLIST continue
    targetname CDATA #IMPLIED>
<!ELEMENT break EMPTY>
<!ATTLIST break
    targetname CDATA #IMPLIED>
<!ELEMENT conditional-expr ((%expr-elems;),(%expr-elems;),(%expr-elems;))>
<!ELEMENT switch ((%expr-elems;),switch-block+)>
<!ELEMENT switch-block ((case|default-case)+,(%stmt-elems;)*)>
<!ELEMENT case (%expr-elems;)>
<!ELEMENT default-case EMPTY>

=== joaocampinhos/pmp2/Hangman.java.xml
<?xml version="1.0"?>
<!DOCTYPE java-source-program SYSTEM "java-ml.dtd">
<java-source-program>
<java-class-file name="Hangman.java">
<import module="java.awt.*"/>
<import module="java.awt.event.*"/>
<import module="java.applet.*"/>
<import module="java.io.*"/>
<import module="java.net.*"/>
<class name="Hangman" visibility="public" line="45" col="0" end-line="558" end-col="0" comment="/*
 * @(#)Hangman.java1.5  03 Apr 1996 10:56:25
 *
 * Copyright (c) 1994-1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL or COMMERCIAL purposes and
 * without fee is hereby granted. 
 * Please refer to the file http://java.sun.com/copy_trademarks.html
 * for further important copyright and trademark information and to
 * http://java.sun.com/licensing.html for further important licensing
 * information for the Java (tm) Technology.
 * 
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 * 
 * THIS SOFTWARE IS NOT DESIGNED OR INTENDED FOR USE OR RESALE AS ON-LINE
 * CONTROL EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE
 * PERFORMANCE, SUCH AS IN THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
 * NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, DIRECT LIFE
 * SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN WHICH THE FAILURE OF THE
 * SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL INJURY, OR SEVERE
 * PHYSICAL OR ENVIRONMENTAL DAMAGE (&quot;HIGH RISK ACTIVITIES&quot;).  SUN
 * SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR
 * HIGH RISK ACTIVITIES.
 *
 * @author Patrick Chan
 * modified to use MediaTracker by
 * @author Herb Jellinek
 * modified for 1.1 by
 * @author Chris Bucchere
 *
 */">
  <superclass name="java.applet.Applet"/>
  <implement interface="java.lang.Runnable"/>
  <implement interface="java.awt.event.MouseListener"/>
  <implement interface="java.awt.event.KeyListener"/>
  <field name="maxTries" final="true" line="50" col="2" end-line="50" end-col="24" comment="/* This is the maximum number of incorrect guesses. */"><type name="int" primitive="true"/><literal-number kind="integer" value="5"/></field>
  <field name="maxWordLen" final="true" line="53" col="2" end-line="53" end-col="27" comment="/* This is the maximum length of a secret word. */"><type name="int" primitive="true"/><literal-number kind="integer" value="20"/></field>
  <field name="secretWord[]" line="56" col="2" end-line="56" end-col="19" comment="/* This buffer holds the letters in the secret word. */"><type name="char" primitive="true"/></field>
  <field name="secretWordLen" line="59" col="2" end-line="59" end-col="19" comment="/* This is the length of the secret word. */"><type name="int" primitive="true"/></field>
  <field name="wrongLetters[]" line="63" col="2" end-line="63" end-col="21" comment="/* This buffer holds the letters which the user typed
     but don't appear in the secret word. */"><type name="char" primitive="true"/></field>
  <field name="wrongLettersCount" line="66" col="2" end-line="66" end-col="23" comment="/* This is the current number of incorrect guesses. */"><type name="int" primitive="true"/></field>
  <field name="word[]" line="70" col="2" end-line="70" end-col="13" comment="/* This buffer holds letters that the user has successfully
     guessed. */"><type name="char" primitive="true"/></field>
  <field name="wordLen" line="73" col="2" end-line="73" end-col="13" comment="/* Number of correct letters in 'word'. */"><type name="int" primitive="true"/></field>
  <field name="wordFont" line="76" col="2" end-line="76" end-col="15" comment="/* This is the font used to paint correctly guessed letters. */"><type name="java.awt.Font"/></field>
  <field name="wordFontMetrics" line="77" col="2" end-line="77" end-col="29" comment=""><type name="java.awt.FontMetrics"/></field>
  <field name="tracker" line="80" col="2" end-line="80" end-col="22" comment="/* This is the MediaTracker that looks after loading the images. */"><type name="java.awt.MediaTracker"/></field>
  <field name="DANCECLASS" final="true" static="true" line="83" col="2" end-line="83" end-col="33" comment="/* These are the various classes of images we load */"><type name="int" primitive="true"/><literal-number kind="integer" value="0"/></field>
  <field name="HANGCLASS" final="true" static="true" line="84" col="2" end-line="84" end-col="32" comment=""><type name="int" primitive="true"/><literal-number kind="integer" value="1"/></field>
  <field name="hangImages[]" line="87" col="2" end-line="87" end-col="20" comment="/* This is the sequence of images for Duke hanging on the gallows. */"><type name="java.awt.Image"/></field>
  <field name="hangImagesWidth" final="true" line="88" col="2" end-line="88" end-col="32" comment=""><type name="int" primitive="true"/><literal-number kind="integer" value="39"/></field>
  <field name="hangImagesHeight" final="true" line="89" col="2" end-line="89" end-col="33" comment=""><type name="int" primitive="true"/><literal-number kind="integer" value="58"/></field>
  <field name="danceThread" line="94" col="2" end-line="94" end-col="20" comment="// Dancing Duke related variables/* This thread makes Duke dance. */"><type name="java.lang.Thread"/></field>
  <field name="danceImages[]" line="97" col="2" end-line="97" end-col="21" comment="/* These are the images that make up the dance animation. */"><type name="java.awt.Image"/></field>
  <field name="danceImageWidths[]" visibility="private" line="98" col="2" end-line="98" end-col="65" comment=""><type name="int" primitive="true"/><array-initializer length="7"><literal-number kind="integer" value="70"/><literal-number kind="integer" value="85"/><literal-number kind="integer" value="87"/><literal-number kind="integer" value="90"/><literal-number kind="integer" value="87"/><literal-number kind="integer" value="85"/><literal-number kind="integer" value="70"/></array-initializer>
  </field>
  <field name="danceHeight" line="101" col="2" end-line="101" end-col="22" comment="/* This is the maximum width and height of all the dance images. */"><type name="int" primitive="true"/><literal-number kind="integer" value="68"/></field>
  <field name="danceImagesLen" line="104" col="2" end-line="104" end-col="24" comment="/* This variable holds the number of valid images in danceImages. */"><type name="int" primitive="true"/><literal-number kind="integer" value="0"/></field>
  <field name="danceImageOffsets[]" visibility="private" line="109" col="2" end-line="109" end-col="62" comment="/* These offsets refer to the dance images.  The dance images
     are not of the same size so we need to add these offset 
     in order to make the images &quot;line&quot; up. */"><type name="int" primitive="true"/><array-initializer length="7"><literal-number kind="integer" value="8"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="8"/><literal-number kind="integer" value="18"/><literal-number kind="integer" value="21"/><literal-number kind="integer" value="27"/></array-initializer>
  </field>
  <field name="danceSequence[]" visibility="private" line="113" col="2" end-line="114" end-col="70" comment="/* This represents the sequence to display the dance images
     in order to make Duke &quot;dance&quot;.  */"><type name="int" primitive="true"/><array-initializer length="23"><literal-number kind="integer" value="3"/><literal-number kind="integer" value="4"/><literal-number kind="integer" value="5"/><literal-number kind="integer" value="6"/><literal-number kind="integer" value="6"/><literal-number kind="integer" value="5"/><literal-number kind="integer" value="6"/><literal-number kind="integer" value="6"/><literal-number kind="integer" value="5"/><literal-number kind="integer" value="4"/><literal-number kind="integer" value="3"/><literal-number kind="integer" value="2"/><literal-number kind="integer" value="1"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="1"/><literal-number kind="integer" value="2"/><literal-number kind="integer" value="2"/><literal-number kind="integer" value="1"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="0"/><literal-number kind="integer" value="1"/><literal-number kind="integer" value="2"/></array-initializer>
  </field>
  <field name="danceSequenceNum" line="118" col="2" end-line="118" end-col="27" comment="/* This is the current sequence number.  -1 implies
     that Duke hasn't begun to dance. */"><type name="int" primitive="true"/><unary-expr op="-"><literal-number kind="integer" value="1"/></unary-expr></field>
  <field name="danceX" line="123" col="2" end-line="123" end-col="16" comment="/* This variable is used to adjust Duke's x-position while
     he's dancing. */"><type name="int" primitive="true"/><literal-number kind="integer" value="0"/></field>
  <field name="danceDirection" line="127" col="2" end-line="127" end-col="24" comment="/* This variable specifies the currently x-direction of
     Duke's dance.  1=&gt;right and -1=&gt;left. */"><type name="int" primitive="true"/><literal-number kind="integer" value="1"/></field>
  <field name="danceMusic" line="130" col="2" end-line="130" end-col="22" comment="/* This is the stream for the dance music. */"><type name="java.applet.AudioClip"/></field>
  <method name="init" visibility="public" id="Hangman:mth-205" line="135" col="2" end-line="176" end-col="2" comment="/**
   * Initialize the applet. Resize and load images.
   */">
    <type name="void" primitive="true"/>
